<?php 
/**
 * In order to keep all sites in sync we are using PHP to sync our ACF fields
 */
// if( function_exists('acf_add_local_field_group') ):

// 	acf_add_local_field_group(array(
// 		'key' => 'group_5fc739018a67b',
// 		'title' => 'Channel Information',
// 		'fields' => array(
// 			array(
// 				'key' => 'field_5fc7390872e4d',
// 				'label' => 'Channel ID',
// 				'name' => 'channel_id',
// 				'type' => 'text',
// 				'instructions' => 'The YouTube Channel ID',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'default_value' => '',
// 				'placeholder' => '',
// 				'prepend' => '',
// 				'append' => '',
// 				'maxlength' => '',
// 			),
// 			array(
// 				'key' => 'field_600a24919cb9f',
// 				'label' => 'Twitch',
// 				'name' => 'twitch',
// 				'type' => 'url',
// 				'instructions' => '',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'default_value' => '',
// 				'placeholder' => '',
// 			),
// 			array(
// 				'key' => 'field_5fc9d0948331a',
// 				'label' => 'Cached Channel Info',
// 				'name' => 'cached_channel_info',
// 				'type' => 'textarea',
// 				'instructions' => 'Save a cache of the channel info here so we don\'t use up our quota',
// 				'required' => 0,
// 				'conditional_logic' => array(
// 					array(
// 						array(
// 							'field' => 'field_5fc7390872e4d',
// 							'operator' => '!=empty',
// 						),
// 						array(
// 							'field' => 'field_5fc7390872e4d',
// 							'operator' => '==empty',
// 						),
// 					),
// 				),
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'default_value' => '',
// 				'placeholder' => '',
// 				'maxlength' => '',
// 				'rows' => '',
// 				'new_lines' => '',
// 			),
// 			array(
// 				'key' => 'field_5fc9b8844e129',
// 				'label' => 'Cached Video List',
// 				'name' => 'cached_video_list',
// 				'type' => 'textarea',
// 				'instructions' => 'Save a cache of the channel list here so we don\'t use up our quota',
// 				'required' => 0,
// 				'conditional_logic' => array(
// 					array(
// 						array(
// 							'field' => 'field_5fc7390872e4d',
// 							'operator' => '!=empty',
// 						),
// 						array(
// 							'field' => 'field_5fc7390872e4d',
// 							'operator' => '==empty',
// 						),
// 					),
// 				),
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'default_value' => '',
// 				'placeholder' => '',
// 				'maxlength' => '',
// 				'rows' => '',
// 				'new_lines' => '',
// 			),
// 			array(
// 				'key' => 'field_5fc9ace80c917',
// 				'label' => 'Host',
// 				'name' => 'host',
// 				'type' => 'text',
// 				'instructions' => '',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'default_value' => '',
// 				'placeholder' => '',
// 				'prepend' => '',
// 				'append' => '',
// 				'maxlength' => '',
// 			),
// 			array(
// 				'key' => 'field_5fcc880337a35',
// 				'label' => 'Active?',
// 				'name' => 'active',
// 				'type' => 'true_false',
// 				'instructions' => 'Is this creator still actively creating videos?',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'message' => '',
// 				'default_value' => 1,
// 				'ui' => 0,
// 				'ui_on_text' => '',
// 				'ui_off_text' => '',
// 			),
// 			array(
// 				'key' => 'field_5fcc8dac3cf36',
// 				'label' => 'Channel Info',
// 				'name' => '',
// 				'type' => 'tab',
// 				'instructions' => '',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'placement' => 'top',
// 				'endpoint' => 0,
// 			),
// 			array(
// 				'key' => 'field_5fcc8dba0502e',
// 				'label' => 'Social',
// 				'name' => '',
// 				'type' => 'tab',
// 				'instructions' => '',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'placement' => 'top',
// 				'endpoint' => 0,
// 			),
// 			array(
// 				'key' => 'field_5fcc8e7b0502f',
// 				'label' => 'Patreon',
// 				'name' => 'patreon',
// 				'type' => 'url',
// 				'instructions' => '',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'default_value' => '',
// 				'placeholder' => '',
// 			),
// 			array(
// 				'key' => 'field_5fcc8e8405030',
// 				'label' => 'Twitter',
// 				'name' => 'twitter',
// 				'type' => 'url',
// 				'instructions' => '',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'default_value' => '',
// 				'placeholder' => '',
// 			),
// 			array(
// 				'key' => 'field_5fcc8efe03eb6',
// 				'label' => 'Website',
// 				'name' => 'website',
// 				'type' => 'url',
// 				'instructions' => '',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'default_value' => '',
// 				'placeholder' => '',
// 			),
// 			array(
// 				'key' => 'field_600a24979cba0',
// 				'label' => 'Instagram',
// 				'name' => 'instagram',
// 				'type' => 'url',
// 				'instructions' => '',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'default_value' => '',
// 				'placeholder' => '',
// 			),
// 			array(
// 				'key' => 'field_600a249d9cba1',
// 				'label' => 'Facebook',
// 				'name' => 'facebook',
// 				'type' => 'url',
// 				'instructions' => '',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'default_value' => '',
// 				'placeholder' => '',
// 			),
// 			array(
// 				'key' => 'field_600a24a792ebc',
// 				'label' => 'TikTok',
// 				'name' => 'tiktok',
// 				'type' => 'url',
// 				'instructions' => '',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'default_value' => '',
// 				'placeholder' => '',
// 			),
// 		),
// 		'location' => array(
// 			array(
// 				array(
// 					'param' => 'post_type',
// 					'operator' => '==',
// 					'value' => 'channels',
// 				),
// 			),
// 		),
// 		'menu_order' => 0,
// 		'position' => 'normal',
// 		'style' => 'default',
// 		'label_placement' => 'top',
// 		'instruction_placement' => 'label',
// 		'hide_on_screen' => '',
// 		'active' => true,
// 		'description' => '',
// 		'modified' => 1611277579,
// 		'local_file' => 'D:wamp64/www/narrative/wp-content/themes/narrative/includes/acf-json/group_5fc739018a67b.json',
// 	));
	
// 	endif;